<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::create([
            [
                'name' => 'Pizza',
                'flavor' => 'Flavor 1',
                'description' => 'Description 1',
                'size' => 'G',
                'pieces' => 10,
                'image' => 'image1.jpg',
                'price' => 9.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Product 2',
                'flavor' => 'Flavor 2',
                'description' => 'Description 2',
                'size' => 'G',
                'pieces' => 5,
                'image' => 'image2.jpg',
                'price' => 14.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Product 3',
                'flavor' => 'Flavor 3',
                'description' => 'Description 3',
                'size' => 'Size 3',
                'pieces' => 8,
                'image' => 'image3.jpg',
                'price' => 12.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Product 4',
                'flavor' => 'Flavor 4',
                'description' => 'Description 4',
                'size' => 'Size 4',
                'pieces' => 6,
                'image' => 'image4.jpg',
                'price' => 10.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Product 5',
                'flavor' => 'Flavor 5',
                'description' => 'Description 5',
                'size' => 'Size 5',
                'pieces' => 12,
                'image' => 'image5.jpg',
                'price' => 8.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Product 6',
                'flavor' => 'Flavor 6',
                'description' => 'Description 6',
                'size' => 'Size 6',
                'pieces' => 4,
                'image' => 'image6.jpg',
                'price' => 11.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Product 7',
                'flavor' => 'Flavor 7',
                'description' => 'Description 7',
                'size' => 'Size 7',
                'pieces' => 9,
                'image' => 'image7.jpg',
                'price' => 13.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Product 8',
                'flavor' => 'Flavor 8',
                'description' => 'Description 8',
                'size' => 'Size 8',
                'pieces' => 7,
                'image' => 'image8.jpg',
                'price' => 15.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Product 9',
                'flavor' => 'Flavor 9',
                'description' => 'Description 9',
                'size' => 'Size 9',
                'pieces' => 11,
                'image' => 'image9.jpg',
                'price' => 7.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Product 10',
                'flavor' => 'Flavor 10',
                'description' => 'Description 10',
                'size' => 'Size 10',
                'pieces' => 3,
                'image' => 'image10.jpg',
                'price' => 9.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Product 11',
                'flavor' => 'Flavor 11',
                'description' => 'Description 11',
                'size' => 'Size 11',
                'pieces' => 6,
                'image' => 'image11.jpg',
                'price' => 12.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Product 12',
                'flavor' => 'Flavor 12',
                'description' => 'Description 12',
                'size' => 'Size 12',
                'pieces' => 4,
                'image' => 'image12.jpg',
                'price' => 11.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Product 13',
                'flavor' => 'Flavor 13',
                'description' => 'Description 13',
                'size' => 'Size 13',
                'pieces' => 8,
                'image' => 'image13.jpg',
                'price' => 14.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Product 14',
                'flavor' => 'Flavor 14',
                'description' => 'Description 14',
                'size' => 'Size 14',
                'pieces' => 5,
                'image' => 'image14.jpg',
                'price' => 10.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Product 15',
                'flavor' => 'Flavor 15',
                'description' => 'Description 15',
                'size' => 'Size 15',
                'pieces' => 3,
                'image' => 'image15.jpg',
                'price' => 7.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
